### ISSUE TITLE
biosh

### ISSUE THREAD

**Issue by oksanaivanovaa** [oksanaivanovaa/1sem_PythonProgramming_HWs#11]
Thank you! OK :)

**Comment by YakutovDmitriy** [comment]
You don't make me wait a lot, good :)

**Comment by oksanaivanovaa** [comment]
But I only didn't prepare examples of using this code. Is it OK?

**Comment by oksanaivanovaa** [comment]
Of course I've tested that

**Comment by YakutovDmitriy** [comment]
Yeah, current implementation works good. You can add some bonus features if you want
